# Generated by Django 3.1 on 2021-04-22 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of question', max_length=200, verbose_name='Title of question')),
                ('body', models.TextField(verbose_name='The question')),
                ('publish', models.DateTimeField(auto_now_add=True, help_text='The publish date of post')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='The last update')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
                'unique_together': {('author', 'publish')},
            },
        ),
    ]
